kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  redis.conf: |
    {{- include "redis.conf" . | nindent 4 -}}
