apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
    spec:
      serviceAccountName: {{ $.Release.Name }}
      containers:
      - name: {{ $.Release.Name }}
        image: "pickledish/cbnr:{{ $.Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        # this is what starts the container in "query" mode
        args:
        - query
        env:
        - name: PERMISSIVE_MODE
          value: "false"
        - name: HTTP_LISTENER_PORT
          value: "8080"
        - name: INFLUX_URL
          value: "http://influxdb.default:8086"
        - name: INFLUX_DB_NAME
          value: "testdb"
        - name: CORS_ALLOWED_ORIGIN
          value: "https://app.cbnr.xyz"
        # equivalent to "docker run --expose", so no need for EXPOSE in dockerfile
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
