kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  .dockerconfigjson: {{ $.Values.config_json | b64enc }}
type: kubernetes.io/dockerconfigjson
