apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8517
    targetPort: 8517
    protocol: UDP
  selector:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
