kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-sql
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
data:
  accesslog.sql: |
    {{- include "accesslog.sql" . | nindent 4 -}}
