apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "config.yml" . | sha256sum }}
        checksum/sql: {{ include "accesslog.sql" . | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9363"
      labels:
        app: {{ $.Chart.Name }}
        release: {{ $.Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ $.Release.Name }}
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:{{ $.Chart.AppVersion }}
        ports:
        - containerPort: 8123
          protocol: TCP
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9363
          protocol: TCP
        # todo, confirm
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
        - name: {{ $.Release.Name }}-data
          mountPath: /var/lib/clickhouse/
        - name: {{ $.Release.Name }}-config
          mountPath: /etc/clickhouse-server/config.d/config.yml
          subPath: config.yml
          # note, the below doesn't actually work for executing SQL at pod start
        - name: {{ $.Release.Name }}-sql
          mountPath: /docker-entrypoint-initdb.d/accesslog.sql
          subPath: accesslog.sql
      volumes:
      - name: {{ $.Release.Name }}-config
        configMap:
          name: {{ $.Release.Name }}-config
      - name: {{ $.Release.Name }}-sql
        configMap:
          name: {{ $.Release.Name }}-sql
  volumeClaimTemplates:
  - metadata:
      name: {{ $.Release.Name }}-data
    spec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: "local-path"
      resources:
        requests:
          storage: 10Gi
