kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-config
  labels:
    app: {{ $.Chart.Name }}
data:
  # this works as intended -- certs aren't renewed upon Caddy restart
  # when this cache is mounted and has valid certs already, so less
  # risk of hitting LE rate limit
  caddy.json: |
    {{- include "caddy.config" . | nindent 4 -}}
