kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-config
  labels:
    app: {{ $.Chart.Name }}
data:
  Caddyfile: |
    {
      email brandon@willett.io
      # this might be a decent problem
      # i don't think caddy checks this location for existing certs at startup
      # before it attempts to get new certs from lets encrypt, etc
      # so restarting caddy one too many times might blow the rate limit??
      storage file_system /var/lib/caddy/.local/share/caddy
    }

    api.cbnr.xyz {
      log
      reverse_proxy /query serve.default:8080
    }
